### ISSUE TITLE
Problem with CounterCache

### ISSUE THREAD

**Issue by lorro** [josbeir/image#10]
If a Model implements both the ImageBehavior as the CounterCacheBehavior things are going wrong.
I have UsersTable that uses both and when I try to save I get following error

```mysql
SELECT (COUNT(*)) AS `count` FROM users Users LEFT JOIN images Users_image_image 
ON (Users_image_image.model = :c0 AND 
Users_image_image.field = :c1 AND Users.id = (Users_image_image.foreign_key)) WHERE user_id = :c2
```

**Comment by josbeir** [comment]
A bit late but, I don't think this error is related to the behavior itself.
