### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by w-mazed** [josbeir/image#12]
Hi,

In the ImageHelper you changed the params of url function, the second param must be now a string not a array, so please update the documentation from:

`$this->Image->url($entity->field, [ 'preset' => 'presetName' ]); // Returns the image path`

to:

`$this->Image->url($entity->field, 'presetName'); // Returns the image path`

Thanks.

**Comment by josbeir** [comment]
tnx, done!

PR's are always welcome by the way :-)

**Comment by w-mazed** [comment]
😄 I noted that 👍
