### ISSUE TITLE
SQL error when Behavior is used inside model with validateUnique validation rule.

### ISSUE THREAD

**Issue by marcon100** [josbeir/image#2]
Hi,

at the beginning I want to thank you for this great plugin ;) I discovered a issue I think. Behavior do not seems to work properly with models that has **validateUnique** validation rule. Here is part of my Users model validation:

``` php
->add('login', 'unique', ['rule' => 'validateUnique', 'provider' => 'table'])
```

Behavior configuration looks like this:

``` php
$this->addBehavior('Image.Image', [
                    'table' => 'images',
                    'path' => WWW_ROOT . 'avatars',
                    'presets' => [
                        'overview' => [
                            'resize' => [ 200, 200, 'outside', 'fill' ],
                            'crop' => [ 'center', 'center', 200, 200 ]
                        ]
                    ],
                    'fields' => [
                        'avatar' => 'one'
                    ],
        ]);
```

When I'm trying to preform Users->save I have the following error:
_Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous_

SQL query looks like this:

```
SELECT 1 AS `existing` FROM `users` `Users` LEFT JOIN `images` `Users_avatar_image` ON (`Users_avatar_image`.`model` = :c0 AND `Users_avatar_image`.`field` = :c1 AND `Users`.`id` = (`Users_avatar_image`.`foreign_key`)) WHERE (`login` = :c2 AND NOT (`id` = :c3)) LIMIT 1
```

From what I can tell behavior adds inner query in beforeFind function for queries that are created by validator which in turn causes an error that I'm dealing with since those queries do not use table aliases in WHERE clause. Is it a bug indeed or is it caused by incorrect configuration from my side? Thanks for help :)

**Comment by josbeir** [comment]
Hi,

Yeah i see why this is happening. the field 'id' is ambiguous because validateUnique is not adding the proper table name to the generated conditions array. Ideally cake's Cake\ORM\Table::validateUnique function should add the table name in it's generated condition like the modified function below. If you want a quick fix you could paste this (updated) function in your model and it should work.

``` php
    public function validateUnique($value, array $options, array $context = []) {
        if (empty($context)) {
            $context = $options;
        }

        $conditions = [$context['field'] => $value];
        if (!empty($options['scope']) && isset($context['data'][$options['scope']])) {
            $scope = $options['scope'];
            $scopedValue = $context['data'][$scope];
            $conditions[$scope] = $scopedValue;
        }

        if (!$context['newRecord']) {
            $keys = (array)$this->primaryKey();
            $not = [];
            foreach ($keys as $key) {
                if (isset($context['data'][$key])) {
                    $not[$this>alias() .'.'. $key] = $context['data'][$key]; <== add table name
                }
            }
            $conditions['NOT'] = $not;
        }

        return !$this->exists($conditions);
    }
```

Another option would be to load add the behavior after validation in the afterValidate.

I'm not really sure how to cleanly detect when the behavior should attach itself and when not. There is already an option to disable attaching in find queries like this:

`$this->find('all', [ 'images' => false ])->conditions(....);` but that's not an option in this case. Maybe configurable setting to only do the containing magic on demand...

**Comment by marcon100** [comment]
Hi,

Thanks for answer. From what I can tell this error doesn't happen anymore. validateUnique has been changed recently so I don't think that any changes has to be made in Behavior itself. Again, thanks for help.

**Comment by lorro** [comment]
Hi,

Great plugin, really like the idea behind it ;-)

Though I stumbled upon the same exact error in the cooperation of your plugin and the Tools.PasswordableBehavior of @dereuromark.

In the 2 functions where the PasswordableBehavior does its password validation the following query is executed: `$dbValue = $this->_table->find()->where([$this->_table->primaryKey() => $primaryKey])->first();`

If I manually add `$this->_table->alias()` before that primarykey param it works perfectly fine as I expected but of course it's not really good practice to make changes myself in a plugin file.

Did you by now find a working solution to overcome this issue (see comments above)? Or should I try ask @dereuromark if he's willing to reflect those changes in his plugin code?

Thanks!

**Comment by dereuromark** [comment]
Yes please provide a PR to fix this :) would be awesome

**Comment by josbeir** [comment]
Thanks for reporting, I'll look into this asap
