### ISSUE TITLE
Upload many

### ISSUE THREAD

**Issue by forstjiri** [josbeir/image#3]
Hi, 
i tried using you behavior in CakePHP 3.1 . It seems to be just what i need except its not uploading multiple images.
This line `'images' => 'many'` should do that right?
It always uploads just one line.

Thanks for you work.

**Comment by josbeir** [comment]
Can you provide me an example of your code? How did you implement the multiple images form etc? Thanks! J

Make sure you pass your images following cake guidelines: 

view:

``` php
<?= $this->Form->create($entity, [ 'type' => 'file' ]); ?>
    <?= $this->Form->input('images.0, [ 'type' => 'file', 'label' => false ]) ?>
    <?= $this->Form->input('images.1, [ 'type' => 'file', 'label' => false ]) ?>
    <?= $this->Form->input('images.2, [ 'type' => 'file', 'label' => false ]) ?>
<?= $this->Form->end(); ?>
```

controller:

``` php
public function add($entity_id = null)
{
    $entity = $this->Table->newEntity();

    if ($entity_id) {
        $entity = $this->Table->get($entity_id);
    }

    if ($this->request->is(['post', 'put'])) {
        $entity = $this->Table->patchEntity($entity, $this->request->data());

        if ($this->Table->save($entity)) {
            $this->redirect(['action' => 'index']);
        }
    }

    $this->set(compact('entity'));
}
```

table:

``` php
public function initialize(array $config)
{
    $this->addBehavior('Image.Image', [
        'path' => WWW_ROOT . 'media',
        'presets' => [
            'thumb' => [
                'fit' => [ 80, 50 ],
            ]
        ],
        'fields' => [
            'images'  => 'many'
        ]
    ]);
}
```

**Comment by forstjiri** [comment]
Thanks, i got it now :) 
I thought that it is just supposed to pile up images, not replace them.
So i used square brackets notation and it works now when i upload multiple. Thanks for your work :)

```
echo $this->Form->file('images[]', ['type' => 'image', 'multiple' => true]);

```

**Comment by forstjiri** [comment]
BTW, maybe you could write short info to .md, how to use this behavior in view to upload multiple images.

**Comment by tgoeminne** [comment]
When you use multiple is true. It gives problems when you add more files in a second upload, you need to change the keys so they are not same as the field_index values, otherwise will overwrite existing files?
