### ISSUE TITLE
using images and main

### ISSUE THREAD

**Issue by tgoeminne** [josbeir/image#6]
Hi,

I am trying to get this to work with images and main fields. I assume it is used to pick an image as the thumbnail image?

In my code I have input field on add form:

<?php echo $this->Form->file('images[]', ['type' => 'image', 'multiple' => true]); ?>

Then I can attach multiple images at once. I want to set the first image as the main image. So I do the following:

$this->request->data['main'] = $this->request->data['images']['0'];
unset($this->request->data['images']['0']);

But then the main image does not get stored. Can you point out how this should be done. Also changing an image from field images to main, has the field_index any influence?

**Comment by josbeir** [comment]
You should set the Behavior so that fields 'main' and 'images' are both parsed and de data should be set up correctly in the entity
