### ISSUE TITLE
parent_id

### ISSUE THREAD

**Issue by tgoeminne** [josbeir/image#7]
HI,

I am wonder how the relation is defined for this model? 

I have an article and then parent_id, when I want to collect the main article with children, the images are not bound to the children?

Greets,
Thomas

**Comment by tgoeminne** [comment]
Is this plugin dead????

**Comment by tgoeminne** [comment]
See example:

$this->belongsTo('Variations', [
        	'className' => 'Articles',
        	'foreignKey' => 'parent_id'
        ]);

Then when search for articles and use contain => Variations.images, the images show up as empty...

**Comment by josbeir** [comment]
Not dead, just a bit dorment :-) 

Its a bit unclear what the issue is, could you maybe include a full snippet of what you did and you expect to happen?

**Comment by tgoeminne** [comment]
Hi,

It's been a while. I have managed to get everything to work the way I wanted it. I don't actually remember anymore since it's so long...

Gr

**Comment by josbeir** [comment]
Alright! I'll close it then
